import { getServerSession } from 'next-auth'

import SessionProvider from '@/components/SessionProvider'
import "@/style/tailwind.css";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Layout({ children}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}