import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";

import SessionProvider from "@/components/SessionProvider";
import "@/style/tailwind.css";

//Component
import Navbar from "@/components/Navbar-login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const session = await getServerSession();

  console.log("Rendering Dashboard Layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
